### ISSUE TITLE
How to make dolphin all blurred?

### ISSUE THREAD

**Issue by thoriqadillah** [yeyushengfan258/We10XOS-kde#10]
Why my dolphin folder area is not blurred like the screenshot you provided? Is something I missed or maybe I need some configuration? I want the all blurred thing. Sorry, I'm new in kde and linux
![image](https://user-images.githubusercontent.com/44075782/175758290-5737c58f-1e2e-4f92-99a9-3f4fc210a07d.png)

**Comment by bnhr** [comment]
Have you configure your kvantum? And using it inside Application Style?

**Comment by thoriqadillah** [comment]
@bnhr oh right. it's done now, thank you very much for the theme. I love it
