### ISSUE TITLE
Titlebar blur doesn't work on Plasma 5.25

### ISSUE THREAD

**Issue by aionescu** [yeyushengfan258/We10XOS-kde#8]
Titlebar and other decorations aren't blurred on Plasma 5.25.

After some investigation, this seems to be caused by the kornerbug fix, and `decoration.svg` needs to be updated.

More info:
https://www.reddit.com/r/kde/comments/vcee6z/titlebar_blur_gone_on_plasma_525/
https://psifidotos.blogspot.com/2022/03/kornersfix.html

**Comment by yeyushengfan258** [comment]
Is the problem solved?

**Comment by aionescu** [comment]
Yes, @korapp's PR fixed the issue for me.
